import SettingSidebar from "@/app/_components/settings/SettingSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className={` darkTheme flex  bg-[#f6faff] h-screen`}>
        <SettingSidebar />
        <div className=" overflow-y-auto relative flex-1 bg-[#f6faff] min-h-screen  text-black">
          {children}
        </div>
      </div>
    </>
  );
}
