'use client'

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "./_components/ThemeProviderWrapper";
import { Provider } from "react-redux";
import { store } from "@/lib/Redux/Store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Social</title>
      <body
        className={`${geistSans.variable} ${geistMono.variable} darkTheme `}
      >
        <ThemeProviderWrapper>
          <Provider store={store}>{children}</Provider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
