import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "./_components/ThemeProviderWrapper";

import { ReduxProvider } from "./ReduxProvider";
import Sidebar from "./_components/home/sidebar/Sidebar";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} darkTheme flex  bg-[#f6faff] h-screen`}
      >
        <ThemeProviderWrapper>
          <ReduxProvider>
            <Sidebar />
            <div id="main" className=" overflow-y-auto relative flex-1 bg-[#f6faff] min-h-screen  text-black">
            {children}
            </div>
            </ReduxProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
