import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "./_components/ThemeProviderWrapper";

import { ReduxProvider } from "./ReduxProvider";
import Sidebar from "./_components/home/sidebar/Sidebar";
import RightSidebar from "./_components/home/rightSidebar/RightSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} darkTheme flex  bg-[#f6faff] h-screen`}
      >
        <ThemeProviderWrapper>
          <ReduxProvider>
            <Sidebar />
            <div id="main" className=" overflow-y-auto relative flex-1 bg-[#f6faff] min-h-screen ">
            {children}
            </div>
            <RightSidebar/>
            </ReduxProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
